// pnpm gen — derives Solidity constants and differential test vectors from
// furnace.config.ts. Contracts never hand-copy a protocol number.
//   contracts/src/generated/FurnaceParams.sol   constants + registry addresses
//   contracts/test/fixtures/oracle-vectors.json reference values from the TS helpers
// pnpm gen --check exits non-zero if either file is stale (CI gate).
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname } from 'node:path';
import cfg, {
  contractAddress, CREATEX_FACTORY, toChecksumAddress, heatMultiplier, cooledAgeAfterWithdrawal, deedHeatAge,
  baseEmissionPerDay, totalMintForEpoch,
} from '../furnace.config';
import { canonicalize, keccakHex } from './canonical';

const PARAMS = 'contracts/src/generated/FurnaceParams.sol';
const VECTORS = 'contracts/test/fixtures/oracle-vectors.json';
const DAY = 86_400;

/** Exact decimal (number or string) → 18-decimal fixed-point integer string. */
function wad(x: number | string): string {
  // Shortest round-trip decimal: 0.3 → "0.3" (exact), never toFixed's binary noise.
  const s = typeof x === 'number' ? (/e/i.test(String(x)) ? x.toFixed(18) : String(x)) : x;
  if (!/^\d+(\.\d+)?$/.test(s)) throw new Error(`wad: unsupported value ${s}`);
  const [i, f = ''] = s.split('.');
  return (BigInt(i) * 10n ** 18n + BigInt((f + '0'.repeat(18)).slice(0, 18))).toString();
}
const pctToWad = (pct: number) => wad(pct / 100);

const f = cfg.forge;
const milestones = f.relics.filter((r) => r.heatBump > 0).sort((a, b) => a.days - b.days);

// ── FurnaceParams.sol ────────────────────────────────────────────────────
const lines: string[] = [];
const c = (type: string, name: string, value: string | number, note = '') =>
  lines.push(`    ${type} internal constant ${name} = ${value};${note ? ' // ' + note : ''}`);

c('bytes32', 'CONFIG_HASH', keccakHex(canonicalize(cfg)), `furnace.config.ts v${cfg.version}`);
lines.push('');
lines.push('    // ── EMBER supply (live-supply ceiling, not cumulative) ──');
if (cfg.token.maxSupply !== cfg.emissions.supplyCeiling.hardCap) throw new Error('maxSupply ≠ hardCap');
c('string', 'EMBER_NAME', JSON.stringify(cfg.token.name));
c('string', 'EMBER_SYMBOL', JSON.stringify(cfg.token.symbol));
if (cfg.token.decimals.evm !== 18) throw new Error('EMBER must have 18 EVM decimals');
c('uint256', 'EMBER_MAX_SUPPLY', `${cfg.token.maxSupply}e18`);
c('uint256', 'EMBER_KINDLING_SEED', `${cfg.token.allocations.kindlingPool}e18`);
c('uint256', 'EMBER_TREASURY_ALLOCATION', `${cfg.token.allocations.treasury.amount}e18`);
c('uint256', 'EMBER_TREASURY_VESTING', `${cfg.token.allocations.treasury.vestingDays} days`);
lines.push('');
lines.push('    // ── Emissions (shape: halfLife) ──');
if (cfg.emissions.base.shape !== 'halfLife') throw new Error('generator supports halfLife only');
c('uint256', 'EPOCH_SECONDS', cfg.emissions.epochSeconds);
c('uint256', 'EMISSION_START_PER_DAY', `${cfg.emissions.base.startPerDay}e18`);
c('uint256', 'EMISSION_FLOOR_PER_DAY', `${cfg.emissions.base.floorPerDay}e18`);
c('uint256', 'EMISSION_HALF_LIFE_DAYS', cfg.emissions.base.halfLifeDays);
c('uint256', 'SPLIT_FLAT_WAD', pctToWad(cfg.emissions.split.flatPct));
c('uint256', 'SPLIT_HEAT_WAD', pctToWad(cfg.emissions.split.heatPct));
c('uint256', 'CONVICTION_BUCKET_WAD', pctToWad(cfg.emissions.convictionBucketPct));
lines.push('');
lines.push('    // ── Heat (shape: sqrt; bumps prorated between milestones) ──');
if (f.heat.shape !== 'sqrt') throw new Error('generator supports sqrt Heat only');
c('uint256', 'HEAT_START_WAD', wad(f.heat.startMultiplier));
c('uint256', 'HEAT_RAMP_BONUS_WAD', wad(f.heat.rampBonus));
c('uint256', 'HEAT_RAMP_SECONDS', `${f.heat.rampDays} days`);
c('uint256', 'MAX_LOTS_PER_POSITION', f.heat.maxLotsPerPosition);
c('uint256', 'MILESTONE_COUNT', milestones.length);
milestones.forEach((m, i) => {
  c('uint256', `MILESTONE_${i}_SECONDS`, `${m.days} days`, m.key);
  c('uint256', `MILESTONE_${i}_BUMP_WAD`, wad(m.heatBump));
});
c('uint256', 'DEED_HEAT_CARRY_WAD', pctToWad(f.deeds.heatCarryPct));
c('uint256', 'MAX_TOTAL_MULTIPLIER_WAD', wad(f.caps.maxTotalMultiplier));
lines.push('');
lines.push('    // ── Deterministic deployment registry (CREATE3). PROVISIONAL while the');
lines.push(`    //    deployer is ${cfg.deployment.evm.deployer} — regenerate after pnpm mine:salts.`);
c('address', 'CREATEX', CREATEX_FACTORY);
for (const n of Object.keys(cfg.deployment.evm.contracts) as Parameters<typeof contractAddress>[0][]) {
  c('address', n.replace(/([a-z])([A-Z])/g, '$1_$2').toUpperCase(), toChecksumAddress(contractAddress(n)));
}


const params = `// SPDX-License-Identifier: MIT
// AUTO-GENERATED by \`pnpm gen\` from furnace.config.ts v${cfg.version}. DO NOT EDIT.
pragma solidity 0.8.28;

/// @notice Protocol constants derived from the canonical config. Contracts read
///         these instead of hard-coding numbers; \`pnpm gen --check\` fails CI if stale.
library FurnaceParams {
${lines.join('\n')}
}
`;

// ── Oracle vectors ───────────────────────────────────────────────────────
const heatAgesDays = [0, 0.5, 1, 6.999, 7, 7.001, 15, 29.99, 30, 30.01, 60, 89.9, 90, 90.1, 135, 179.9, 180, 180.1, 250, 364.9, 365, 365.1, 400, 730, 3650];
const cool: [number, number][] = [[365, 0.01], [365, 0.1], [365, 0.5], [730, 0.5], [100, 0.25], [7, 1], [0, 0.5], [200, 0]];
const deedAges = [0, 1, 100, 365, 730];
const emissionDays = [0, 1, 30, 182, 364, 365, 366, 730, 1095, 1617, 1618, 1619, 1700, 5000];
const mints: [number, number, number][] = [
  [100, 50, 21_000_000 - 90],
  [21_600, 0, 0],
  [21_600, 5_000, 20_990_000],
  [0, 4_000, 20_999_000],
  [1_000, 1_000, 21_000_000],
  [1_000, 1_000, 21_500_000],
];
const secs = (d: number) => String(Math.round(d * DAY));
const vectors = {
  version: cfg.version,
  heat: { ageSeconds: heatAgesDays.map(secs), wad: heatAgesDays.map((d) => wad(heatMultiplier(Math.round(d * DAY) / DAY))) },
  cool: {
    ageSeconds: cool.map(([d]) => secs(d)),
    fractionWad: cool.map(([, x]) => wad(x)),
    expectedSeconds: cool.map(([d, x]) => String(Math.floor(cooledAgeAfterWithdrawal(d, x) * DAY))),
  },
  deed: { ageSeconds: deedAges.map(secs), expectedSeconds: deedAges.map((d) => String(Math.round(deedHeatAge(d) * DAY))) },
  emission: { day: emissionDays.map(String), wad: emissionDays.map((d) => wad(baseEmissionPerDay(d))) },
  mint: {
    base: mints.map(([b]) => wad(b)),
    ashfall: mints.map(([, a]) => wad(a)),
    supply: mints.map(([, , s]) => wad(s)),
    expBase: mints.map(([b, a, s]) => wad(totalMintForEpoch(b, a, s).base)),
    expAshfall: mints.map(([b, a, s]) => wad(totalMintForEpoch(b, a, s).ashfall)),
  },
};
const vectorsJson = JSON.stringify(vectors, null, 2) + '\n';

// ── write or check ───────────────────────────────────────────────────────
const outputs: [string, string][] = [[PARAMS, params], [VECTORS, vectorsJson]];
if (process.argv.includes('--check')) {
  let stale = 0;
  for (const [p, body] of outputs) {
    let cur = '';
    try { cur = readFileSync(p, 'utf8'); } catch { /* missing */ }
    const ok = cur === body;
    if (!ok) stale++;
    console.log(`${ok ? '✓' : '✗'} ${p}${ok ? '' : ' is stale — run pnpm gen'}`);
  }
  process.exit(stale ? 1 : 0);
}
for (const [p, body] of outputs) { mkdirSync(dirname(p), { recursive: true }); writeFileSync(p, body); console.log(`wrote ${p}`); }
